name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the Python version you want to use

      - name: Install dependencies
        run: pip install pylint

      - name: Run pylint on Python files
        run: |
          for file in $(find . -name '*.py'); do
            pylint "$file"
          done
